# Generated by Django 4.1.2 on 2022-10-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_lead_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='lead_text',
            field=models.CharField(blank=True, help_text='Sous-titre sous la bannière', max_length=140),
        ),
    ]
